### ISSUE TITLE
大佬，pixel3的内核怎么编译能简单指导一下吗

### ISSUE THREAD

**Issue by hnzzmyr** [Moe-hacker/Moe-hacker#1]
我从lineageos下载了pixel3的内核源码，但是编译器不管怎么选择都会报错，试了arm的，google的还有一些第三方的，都不行，请问你怎么编译的方便说一下吗，谢谢

**Comment by Moe-hacker** [comment]
> 我从lineageos下载了pixel3的内核源码，但是编译器不管怎么选择都会报错，试了arm的，google的还有一些第三方的，都不行，请问你怎么编译的方便说一下吗，谢谢

我用的aosp里的源码，这是不完全的教程：
https://zhuanlan.zhihu.com/p/447282679
生成boot那段不要听他的，直接找到目录下有一个Image.lz4-dtb(arch/arm64/boot里)，好像是叫这名字的，使用fastboot boot Image.lz4-dtb即可临时启动，刷入的话，使用EX kernel manager这个软件里下载的内核,替换zip中的文件即可
编译时要把所有配置文件里的CONFIG-xxxxx=m改成CONFIG-xxxxx=y,否则各种掉驱动，编译时出现[M]字样就要去找对应的配置文件(上级目录或者在往上里找)
唯一一个不会编译进内核的模块是wifi，名字是wlan.ko，由于源码在另一个文件夹里，所以写了magisk模块用于加载此内核模块

**Comment by Moe-hacker** [comment]
> 我从lineageos下载了pixel3的内核源码，但是编译器不管怎么选择都会报错，试了arm的，google的还有一些第三方的，都不行，请问你怎么编译的方便说一下吗，谢谢

对了，貌似还要改一个配置文件，删掉配置校验否则无法编译，具体挺复杂的😂

**Comment by Moe-hacker** [comment]
> 我从lineageos下载了pixel3的内核源码，但是编译器不管怎么选择都会报错，试了arm的，google的还有一些第三方的，都不行，请问你怎么编译的方便说一下吗，谢谢

Aosp的源码自带编译器，必须好评👍

**Comment by Moe-hacker** [comment]
> 哦哦知乎上的这个帖子我也看见过，但是我是想要开启内核里面一些功能，make menuconfig那个界面好像只有第三方的内核才有，所以我一直在找合适的编译器，aosp的编译器似乎不能用来编译第三方的内核。我现在准备下载lineageos源码里面的编译器了😉多谢大佬🙏话说酷安上你发的docker安装的帖子你删了吗，我后来找不到了

开启内核功能也可以直接修改defconfig来实现，并不一定非得用menuconfig，祝成功😉
